# Site settings
title: itsneufox
description: My personal website
theme: just-the-docs

# URL settings
url: "https://itsneufox.github.io"

# Repository settings
repository: itsneufox/itsneufox.github.io

# Logo
logo: "/assets/images/logo-coloured.png"

# Search settings
search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'

# Navigation settings
nav_enabled: true

# Heading anchor links
heading_anchors: true

# Color scheme
color_scheme: dark

# Auxiliary links
aux_links:
  Template Repository: 
    url: https://github.com/just-the-docs/just-the-docs-template
    icon: fa-solid fa-code-branch

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins (optional)
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Exclude files and directories from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
