title: itsneufox
description: My personal website
theme: just-the-docs

url: "https://itsneufox.github.io"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

repository: itsneufox/itsneufox.github.io

logo: "/assets/images/logo-coloured.webp"